### ISSUE TITLE
Not working using the official DEB package(MultiMC)

### ISSUE THREAD

**Issue by JoeJoeTV** [ShayBox/MultiMC-Twitch#6]
I installed this manually on Linux Mint 20.1 and it didn't work, so I looked around a bit at the output and what gets passed to the program.
I found out that multimc-curseforge was trying to execute the  `multimc` executeable, but couldn't find it.
This is because the MultiMC deb package uses `/opt/multimc/run.sh` to start MultiMC.
I temporarily fixed this by creating a link in `/usr/bin` using `update-alternatives`, but I suppose this isn't a permanent fix.

Maybe this could be fixed by launching MultiMC using the .desktop file? I'm not sure.

**Comment by ShayBox** [comment]
The deb package is not actually multimc, it's a shell script that downloads the tar and extracts it to .local/share/multimc, It's pretty lazy, they could have made an actual deb package, a ppa, or even just used an appimage instead of a tar to make it portable across every distro, but since it's Ubuntu I guess i'll add some code to look for multimc.

**Comment by JoeJoeTV** [comment]
Ah ok, yeah, I actually read about that after. THough I'd still prefer a deb package over an AppImage for home use. Providing both would probably be the best solution, so you can have an installable version and onne that you can use portable.

**Comment by ShayBox** [comment]
If they packaged using appimage it would be easy for distro packagers to repackage, users to run directly, to extract, or to install with appimagelauncher, its even pretty easy to make a script to repackage the appimage to a deb, rpm, etc

**Comment by ShayBox** [comment]
Fix is out in latest release
